stages:

  ingestion:
    cmd: python src/data_ingestion.py

    deps:
      - src/data_ingestion.py
      - data/movies_metadata.csv

    outs:
      - artifacts/raw/raw_data.csv

  validation:
    cmd: python src/data_validation.py
    deps:
      - src/data_validation.py
      - artifacts/raw/raw_data.csv
    outs:
      - artifacts/validation/status.txt

  preprocessing:
  
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - artifacts/raw/raw_data.csv
    outs:
      - artifacts/processed/cleaned_data.csv

  feature_engineering:
    cmd: python src/feature_engineering.py

    deps:
      - src/feature_engineering.py
      - artifacts/processed/cleaned_data.csv

    outs:
      - artifacts/featured/featured_data.csv

      
  feature_store:
    cmd: python src/feature_store.py
    deps:
      - src/feature_store.py
      - artifacts/featured/featured_data.csv
    outs:
      - artifacts/feature_store/features.csv

  split:
    cmd: python src/train_test_split.py

    deps:
      - src/train_test_split.py
      - artifacts/feature_store/features.csv

    params:
      - data_split.test_size
      - data_split.random_state
      - training.target_column

    outs:
      - artifacts/split

  training:
    cmd: python src/model_trainer.py
    deps:
      - src/model_trainer.py
      - artifacts/split
    params:
      - model.n_estimators
      - model.max_depth
    outs:
      - artifacts/model/model.pkl
  evaluation:
    cmd: python src/model_evaluation.py 
    deps:
      - src/model_evaluation.py
      - artifacts/model/model.pkl
      - artifacts/split
    outs:
      - artifacts/evaluation/metrics.json